ACCURACY_PROMPT = """"""

FLUENCY_PROMPT = """"""

TERMINOLOGY_PROMPT = """"""

STYLE_PROMPT = """"""

ADDITION_PROMPT = """"""

OMISSION_PROMPT = """"""

MISTRANSLATION_PROMPT = """"""

UNTRANSLATED_TEXT_PROMPT = """"""

PUNCTUATION_PROMPT = """"""

SPELLING_PROMPT = """"""

GRAMMAR_PROMPT = """"""

REGISTER_PROMPT = """"""

INCONSISTENCY_PROMPT = """"""

CHARACTER_ENCODING_PROMPT = """"""

INAPPROPRIATE_FOR_CONTEXT_PROMPT = """"""

INCONSISTENT_USE_PROMPT = """"""

AWKWARD_PROMPT = """"""

ACCURACY_STAGE3_PROMPT = """"""

FLUENCY_STAGE3_PROMPT = """"""

TERMINOLOGY_STAGE3_PROMPT = """"""

STYLE_STAGE3_PROMPT = """"""